### PR TITLE
Art n msg section

### LINKED ISSUE #4: Render Messages and Art Cards On Homepage
To be done after #1 

Both message and art cards should be rendered together on the home page. Preferably rendered in some sort of psudo random way.

### PR DESCRIPTION
**Pull request by zapplecat**
Render both art and message cards on the frontend, assuming that there's fewer art cards than message cards.

Fixes #4

### CODE REVIEW

**Comment by DuongTyler** [comment]
I'm getting an error when I try to build the project. I rebuilt the database, and there is currently nothing in the db right now:
```
Failed to compile.

[$PWD redacted]/holo-valentine-2021/frontend/src/components/gallery/artworkCard/artworkCard.tsx
TypeScript error in [$PWD]/holo-valentine-2021/frontend/src/components/gallery/artworkCard/artworkCard.tsx(33,39):
Property 'recipient' does not exist on type 'Artwork'.  TS2339

    31 |         this.artwork = props.object;
    32 |         this.username = this.artwork.username ? props.object.username : "Anonymous";
  > 33 |         this.recipient = props.object.recipient;
       |                                       ^
    34 |         this.imageElement = document.createElement("img");
    35 | 
    36 |         this.imageLoaded = this.imageLoaded.bind(this);

```

**Comment by zapplecat** [comment]
> I'm getting an error when I try to build the project. I rebuilt the database, and there is currently nothing in the db right now:
> 
> ```
> Failed to compile.
> 
> [$PWD redacted]/holo-valentine-2021/frontend/src/components/gallery/artworkCard/artworkCard.tsx
> TypeScript error in [$PWD]/holo-valentine-2021/frontend/src/components/gallery/artworkCard/artworkCard.tsx(33,39):
> Property 'recipient' does not exist on type 'Artwork'.  TS2339
> 
>     31 |         this.artwork = props.object;
>     32 |         this.username = this.artwork.username ? props.object.username : "Anonymous";
>   > 33 |         this.recipient = props.object.recipient;
>        |                                       ^
>     34 |         this.imageElement = document.createElement("img");
>     35 | 
>     36 |         this.imageLoaded = this.imageLoaded.bind(this);
> ```

Oh derp, I forgot to change the backend... You can see how the frontend works by changing that to usename for now. I'll fix the backend while you take a look at that.

**Comment by DuongTyler** [comment]
hmm well now there seems to be a CSS problem where the message div goes past the width of the card
image

**Review by DuongTyler — APPROVED** [review]
wohoo, schema changes, my favorite

**Pull request merged**
